# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '-t bwapp'
  displayName: 'build docker image'

- script: |
    docker run -d -p 3005:80 bwapp
  displayName: 'start bwapp'

- powershell: |
    Start-Sleep -Seconds 5  
  displayName: 'delay'

- script: |
    wget http://localhost:3005/install.php?install=yes
  displayName: 'init bwapp'


- script: |
    wget https://github.com/whitehatsec/vantage-prevent-distributions/releases/latest/download/VantagePrevent.deb          
    sudo apt-get install -f ./VantagePrevent.deb
    sudo dast-attacker-cli -init -license-key=11dbc457-356c-4fde-a377-f7408300abce  
  displayName: 'install Prevent'

- script: |
    sudo dast-attacker-cli -output-json=$(Build.ArtifactStagingDirectory)/results.json -output-html=$(Build.ArtifactStagingDirectory)/results.html .scan/*.har
  displayName: 'security scan'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Scan Results'
    publishLocation: 'Container'  
  displayName: 'publish artifacts'
